PROCESS BEFORE OUTPUT.
  CALL SUBSCREEN sc_9000 INCLUDING 'SAPLZT9R_MINESWEEPER'
                                   '4000'.

 MODULE STATUS_9000.
*
PROCESS AFTER INPUT.
 CALL SUBSCREEN sc_9000.
 MODULE USER_COMMAND_9000.
